[gravity]
domain = "gravity"
host = "0.0.0.0:4222"

[subscriber]
subscriberID = "kafka_transmitter"
subscriberName = "Kafka Transmitter"
stateStore = "./statestore"
workerCount = 4
chunkSize = 2048
verbose = true
pipelineStart = 0
pipelineEnd = -1

# Authentication
appID = "anonymous"
accessKey = ""

[initialLoad]
enabled = true
omittedCount = 100000


[rules]
subscription = "./settings/subscriptions.json"

[kafka]
hosts = "kafka1:9092,kafka2:9092"
