[gravity]
domain = "gravity"
host = "0.0.0.0:4222"

[subscriber]
subscriber_id = "kafka_transmitter"
subscriber_name = "Kafka Transmitter"
state_store = "./statestore"
worker_count = 4
verbose = true
pipeline_start = 0
pipeline_end = -1

# Authentication
appID = "anonymous"
accessKey = ""

[initial_load]
enabled = true
omitted_count = 100000


[rules]
subscription = "./settings/subscriptions.json"

[kafka]
hosts = "kafka1:9092,kafka2:9092"
